### ISSUE TITLE
L-function graphs for Hilbert modular forms

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1069]
Hello,

Aren't we supposed to compute all the graphs a priori?
Some of these are quite CPU intensive, e.g.:
http://beta.lmfdb.org/L/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-31.1-a/0/0/
also, some exception is raised while processing the graph, see below.

Also, some of these computations fail completely, and we get a missing graph:
http://beta.lmfdb.org/L/ModularForm/GL2/TotallyReal/4.4.2048.1/holomorphic/4.4.2048.1-578.1-b/0/0/

Here are the tracebacks:
```
Exception on /L/Zeros/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-31.1-a/0/0/ [GET]
Traceback (most recent call last):
  File "/home/lmfdb/sage1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lmfdb/sage1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lmfdb/sage1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lmfdb/sage1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lmfdb/sage1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/main.py", line 826, in zeroesLfunction
    return render_zeroesLfunction(request, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/main.py", line 948, in render_zeroesLfunction
    website_zeros = L.compute_web_zeros(time_allowed = 10)
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/Lfunction_base.py", line 98, in compute_web_zeros
    allZeros = self.compute_heuristic_zeros(**kwargs)
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/Lfunction_base.py", line 118, in compute_heuristic_zeros
    return self.compute_lcalc_zeros(via_N = False, step_size = step_size, upper_bound = upper_bound, lower_bound = lower_bound)
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/Lfunction_base.py", line 137, in compute_lcalc_zeros
    return self.sageLfunction.find_zeros(T1, T2, stepsize)
  File "sage/libs/lcalc/lcalc_Lfunction.pyx", line 291, in sage.libs.lcalc.lcalc_Lfunction.Lfunction.find_zeros (/home/lmfdb/sage1/src/build/cythonized/sage/libs/lcalc/lcalc_Lfunction.cpp:4816)
    sig_on()
  File "sage/ext/interrupt/interrupt.pyx", line 99, in sage.ext.interrupt.interrupt.sig_raise_exception (/home/lmfdb/sage1/src/build/cythonized/sage/ext/interrupt/interrupt.c:1127)
    raise RuntimeError(msg)
RuntimeError: Aborted
```

```
Exception on /L/Zeros/ModularForm/GL2/TotallyReal/4.4.2048.1/holomorphic/4.4.2048.1-578.1-b/0/0/ [GET]
Traceback (most recent call last):
  File "/home/lmfdb/sage1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lmfdb/sage1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lmfdb/sage1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lmfdb/sage1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lmfdb/sage1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/main.py", line 826, in zeroesLfunction
    return render_zeroesLfunction(request, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/main.py", line 948, in render_zeroesLfunction
    website_zeros = L.compute_web_zeros(time_allowed = 10)
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/Lfunction_base.py", line 98, in compute_web_zeros
    allZeros = self.compute_heuristic_zeros(**kwargs)
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/Lfunction_base.py", line 118, in compute_heuristic_zeros
    return self.compute_lcalc_zeros(via_N = False, step_size = step_size, upper_bound = upper_bound, lower_bound = lower_bound)
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/Lfunction_base.py", line 137, in compute_lcalc_zeros
    return self.sageLfunction.find_zeros(T1, T2, stepsize)
  File "sage/libs/lcalc/lcalc_Lfunction.pyx", line 291, in sage.libs.lcalc.lcalc_Lfunction.Lfunction.find_zeros (/home/lmfdb/sage1/src/build/cythonized/sage/libs/lcalc/lcalc_Lfunction.cpp:4816)
    sig_on()
  File "sage/ext/interrupt/interrupt.pyx", line 99, in sage.ext.interrupt.interrupt.sig_raise_exception (/home/lmfdb/sage1/src/build/cythonized/sage/ext/interrupt/interrupt.c:1127)
    raise RuntimeError(msg)
RuntimeError: Aborted
```

**Comment by davidfarmer** [comment]
It is unlikely we are going to have the L-functions of Hilbert modular
forms pre-computed in the next two weeks, so that plan is to hide the
L-function links of those which are too time consuming to compute
in real time.

The time is less of an issue with the cloud version, but the examples
that take a lot of time are also more likely to give incorrect results.

**Comment by jvoight** [comment]
As you see, the error is just an issue with "timeout".  Another solution, compatible with hiding L-functions that are too hard, would be to instead return "graph not available" when timing out (capture the RuntimeError)--at least then it doesn't look like a bug.

**Comment by edgarcosta** [comment]
Hmmm, I agree, we won't have the graphs ready in two weeks...
However, I'm a bit more worried about the first example. Even though it raised an exception, it still makes up a graph and consumes around 40 seconds of cpu time...

**Comment by jvoight** [comment]
@davidfarmer : I need some help to decide which HMF L-functions to hide.  To be honest, if 
http://beta.lmfdb.org/L/ModularForm/GL2/TotallyReal/2.2.5.1/holomorphic/2.2.5.1-31.1-a/0/0/
is already too CPU intensive, then none of them should be computed--the conductor is only 775.  

But perhaps there is some tuning to do here: we decide on fewer digits of precision, shorter x-axis for the graph, etc.?  Surely that will improve the performance.

**Comment by davidfarmer** [comment]
That one did seem to take a long time for the graph, and the zeros
never appeared.

We could try a smaller interval for the graph.  That would have to be
changed dynamically as a function of the conductor, so at this stage
I suggest just hiding those L-functions.

**Comment by jvoight** [comment]
David, the suggestion that we hide them amounts to hiding *all* HMF L-functions.  Is that what you are suggesting?  Seems drastic to me.

**Comment by davidfarmer** [comment]
Maybe if we did everyhting on the interval [-10,10] then we
would not get a time-out error.

I can look into this tomorrow.

**Comment by JohnCremona** [comment]
After PR #1135 the conductor 31 example is fine, while the other one says "L-function not avaiable" which is good.
http://beta.lmfdb.org/L/ModularForm/GL2/TotallyReal/4.4.2048.1/holomorphic/4.4.2048.1-578.1-b/0/0/
does not exactly fail but there is no graph.
Closing.
