### ISSUE TITLE
EllipticCurve/Q download_search

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1179]
From the log (shows up ~19 times):

```
Exception on /EllipticCurve/Q/ [GET]
Traceback (most recent call last):
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/elliptic_curves/elliptic_curve.py", line 86, in rational_elliptic_curves
    return elliptic_curve_search(**request.args)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/elliptic_curves/elliptic_curve.py", line 168, in elliptic_curve_search
    return download_search(info)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/elliptic_curves/elliptic_curve.py", line 548, in download_search
    dltype = info['Submit']
KeyError: 'Submit'
```

**Comment by AndrewVSutherland** [comment]
I looked at the code and cannot see how this can happen.  
download_search is only called in one place, from elliptic_curve_search, 
and it is called only when info['download'] is nonzero.  The only place 
where an attribute called download is set is in search_results.html, 
which also sets Submit.

What are the dates in the log?

**Comment by edgarcosta** [comment]
There are no dates in the flasklog :(
But there are 2015009 lines in the log.

Here are the 19 errors:
 https://gist.github.com/edgarcosta/af7dcfead6e905726e676aba6b0d2f02

**Comment by edgarcosta** [comment]
`grep "GET /EllipticCurve/Q/"  accesslog | grep " HTTP/1.1\" 500"   | grep "/May/2016" | cut -f2- -d- > `
https://gist.github.com/edgarcosta/5487be0752c3457f921c5263c8fb8100

It looks like a bot clicking on the wrong things.

**Comment by JohnCremona** [comment]
I suppose we could add a try: before dltype=info['Submit'] and make the except return nothing.  Just to prevent these extraneous log entries.

**Comment by JohnCremona** [comment]
@edgarcosta Any objection to closing this?

**Comment by edgarcosta** [comment]
@JohnCremona It is totally up to you

**Comment by AndrewVSutherland** [comment]
I don't think the bot will object to closing, and there are a lot of other issues to deal with so I vote close (in fact I will :))
