### ISSUE TITLE
Grand Canyon L-function

### ISSUE THREAD

**Issue by sanni85** [LMFDB/lmfdb#1187]
Grand Canyon L-function: I tried several times, but I can never get to see the graph displayed.
Is that a problem with my connection or not?

http://beta.lmfdb.org/L/ModularForm/GSp4/Q/Maass/GSp4Maass_1_12.4687_4.72095/#footer

**Comment by edgarcosta** [comment]
Here is the traceback:

```
Exception on /L/Plot/ModularForm/GSp4/Q/Maass/GSp4Maass_1_12.4687_4.72095/ [GET]
Traceback (most recent call last):
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/lfunctions/main.py", line 828, in plotLfunction
    return render_plotLfunction(request, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/lfunctions/main.py", line 897, in render_plotLfunction
    data = getLfunctionPlot(request, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/lfunctions/main.py", line 908, in getLfunctionPlot
    arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_dict(request.args))
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/lfunctions/main.py", line 1038, in generateLfunctionFromUrl
    char = arg6, R = arg7, ap_id = arg8)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/lfunctions/Lfunction.py", line 928, in __init__
    self.lfunc_data = LfunctionDatabase.getGenus2Ldata(self.dbid)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/lfunctions/LfunctionDatabase.py", line 59, in getGenus2Ldata
    Lhash = Lpointer['Lhash']
TypeError: 'NoneType' object has no attribute '__getitem__'
Exception on /L/Zeros/ModularForm/GSp4/Q/Maass/GSp4Maass_1_12.4687_4.72095/ [GET]
Traceback (most recent call last):
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lmfdb/sage3/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/lfunctions/main.py", line 841, in zeroesLfunction
    return render_zeroesLfunction(request, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/lfunctions/main.py", line 956, in render_zeroesLfunction
    L = generateLfunctionFromUrl(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_dict(request.args))
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/lfunctions/main.py", line 1038, in generateLfunctionFromUrl
    char = arg6, R = arg7, ap_id = arg8)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/lfunctions/Lfunction.py", line 928, in __init__
    self.lfunc_data = LfunctionDatabase.getGenus2Ldata(self.dbid)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/lfunctions/LfunctionDatabase.py", line 59, in getGenus2Ldata
    Lhash = Lpointer['Lhash']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by davidfarmer** [comment]
The link should be to

/L/ModularForm/GSp4/Q/Maass/1/1/12.46875_4.720951/1.34260324/

because we changed how those L-functions are stored.
