### ISSUE TITLE
Factoring j EllipticCurve/6.6.371293.1/1.1/a/{1,4}

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#1258]
This seem to fail to load most of the times, and when they load it takes forever
http://www.lmfdb.org/EllipticCurve/6.6.371293.1/1.1/a/1
http://www.lmfdb.org/EllipticCurve/6.6.371293.1/1.1/a/4

Here are the tracebacks:

```
Exception on /EllipticCurve/6.6.371293.1/1.1/a/4 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/main.py", line 313, in show_ecnf
    ec = ECNF.by_label(label)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/WebEllipticCurve.py", line 125, in by_label
    return ECNF(data)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/WebEllipticCurve.py", line 116, in __init__
    self.make_E()
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/WebEllipticCurve.py", line 207, in make_E
    self.fact_j = web_latex(j.factor())
  File "sage/rings/number_field/number_field_element.pyx", line 1610, in sage.rings.number_field.number_field_element.NumberFieldElement.factor (/home/sage/sage-7.1/src/build/cythonized/sage/rings/number_field/number_field_element.cpp:17600)
    if not P.is_principal():
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field_ideal.py", line 1176, in is_principal
    self._cache_bnfisprincipal(proof)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field_ideal.py", line 1119, in _cache_bnfisprincipal
    bnf = self.number_field().pari_bnf(proof)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field.py", line 3620, in pari_bnf
    self._pari_bnf = f.bnfinit(1)
  File "sage/libs/pari/auto_gen.pxi", line 3061, in sage.libs.pari.gen.gen_auto.bnfinit (/home/sage/sage-7.1/src/build/cythonized/sage/libs/pari/gen.c:19784)
    pari_catch_sig_on()
  File "src/cysignals/signals.pyx", line 102, in cysignals.signals.sig_raise_exception (build/src/cysignals/signals.c:1158)
RuntimeError: Aborted
Exception on /EllipticCurve/6.6.371293.1/1.1/a/1 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/main.py", line 313, in show_ecnf
    ec = ECNF.by_label(label)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/WebEllipticCurve.py", line 125, in by_label
    return ECNF(data)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/WebEllipticCurve.py", line 116, in __init__
    self.make_E()
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/WebEllipticCurve.py", line 207, in make_E
    self.fact_j = web_latex(j.factor())
  File "sage/rings/number_field/number_field_element.pyx", line 1610, in sage.rings.number_field.number_field_element.NumberFieldElement.factor (/home/sage/sage-7.1/src/build/cythonized/sage/rings/number_field/number_field_element.cpp:17600)
    if not P.is_principal():
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field_ideal.py", line 1176, in is_principal
    self._cache_bnfisprincipal(proof)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field_ideal.py", line 1119, in _cache_bnfisprincipal
    bnf = self.number_field().pari_bnf(proof)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field.py", line 3620, in pari_bnf
    self._pari_bnf = f.bnfinit(1)
  File "sage/libs/pari/auto_gen.pxi", line 3061, in sage.libs.pari.gen.gen_auto.bnfinit (/home/sage/sage-7.1/src/build/cythonized/sage/libs/pari/gen.c:19784)
    pari_catch_sig_on()
  File "src/cysignals/signals.pyx", line 102, in cysignals.signals.sig_raise_exception (build/src/cysignals/signals.c:1158)
RuntimeError: Aborted

Exception on /EllipticCurve/6.6.371293.1/1.1/a/1 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/main.py", line 313, in show_ecnf
    ec = ECNF.by_label(label)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/WebEllipticCurve.py", line 125, in by_label
    return ECNF(data)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/WebEllipticCurve.py", line 116, in __init__
    self.make_E()
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/ecnf/WebEllipticCurve.py", line 207, in make_E
    self.fact_j = web_latex(j.factor())
  File "sage/rings/number_field/number_field_element.pyx", line 1610, in sage.rings.number_field.number_field_element.NumberFieldElement.factor (/home/sage/sage-7.1/src/build/cythonized/sage/rings/number_field/number_field_element.cpp:17600)
    if not P.is_principal():
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field_ideal.py", line 1176, in is_principal
    self._cache_bnfisprincipal(proof)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field_ideal.py", line 1119, in _cache_bnfisprincipal
    bnf = self.number_field().pari_bnf(proof)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field.py", line 3620, in pari_bnf
    self._pari_bnf = f.bnfinit(1)
  File "sage/libs/pari/auto_gen.pxi", line 3061, in sage.libs.pari.gen.gen_auto.bnfinit (/home/sage/sage-7.1/src/build/cythonized/sage/libs/pari/gen.c:19784)
    pari_catch_sig_on()
  File "src/cysignals/signals.pyx", line 102, in cysignals.signals.sig_raise_exception (build/src/cysignals/signals.c:1158)
RuntimeError: Aborted
```

**Comment by JohnCremona** [comment]
For me these do not take "forever" but a couple of seconds.
It might be reasonable though to not display the j-factorizations for larger degree fields (or to store them if we do want to see them).

Opinions please: it would be easy to not compute or display the factorizations of j-invariants over number fields.  In any case Sage only factors elements of number fields when all the primes factors are principal so the code already deals with some j-factorizations not existing.  This all that would be needed would be to comment out lines 203-209 of WebEllipticCurve.py .

**Comment by JohnCremona** [comment]
See PR #1262, waiting to be merged of this is wanted.

**Comment by AndrewVSutherland** [comment]
It's a shame there isn't a "try_to_factor_but_giveup_after_one_second" function in sage.  But I guess my opinion is that we probably shouldn't try to factor.  I can get a1,a2,a3, but I keep getting 502 server error timeouts on http://www.lmfdb.org/EllipticCurve/6.6.371293.1/1.1/a/4 with a message saying try again in 30 seconds (which also doesn't work).

Would it make sense to still factor the j-invariants over quadratic fields?  Or are those also potentially problematic.

**Comment by jvoight** [comment]
I think we should merge #1262 .  My attempt to load the pages timed out after 30 seconds.  (Y'all are there together, so I don't want to be causing problems by meddling.)

We shouldn't be computing a factorization on the fly--indeed, we shouldn't be computing anything nontrivial on the fly.  It's a database.  (So maybe add a field for the factored j-invariant for 2.0.)

**Comment by edgarcosta** [comment]
The 502 is due to the load balancer.

You can go directly:
http://www-central.lmfdb.xyz/EllipticCurve/6.6.371293.1/1.1/a/4
 and see that sometimes it works and it sometimes takes so long that the
worker gets restarted.

**Comment by JohnCremona** [comment]
@jvoight I certainly agree in principal so apologise for not keeping to my own principles.  Not so long ago there was a time when web pages for elliptic curves over Q crashed when the discriminant was more than 2^64 since that was the crossover for Sage to call pari and there was a Sag bug.
A very boring project for someone would be to see what "computations on the fly" are done anywhere;  then as well as (1) one-off computations to do all these once and (2) changing the code to read these instead of computing, we also need (3) change upload scripts.  All easy and tedious.

**Comment by AndrewVSutherland** [comment]
I'm happy to merge, I'm just wondering if we need to disable it unilaterally.  I've been clicking around trying to found the nastiest cases over quadratic and cubic fields and haven't yet found any whose j-invariants did not factor quickly.

**Comment by JohnCremona** [comment]
We could put in a test to only try to factor if (say) the j-invariant's numerator had norm below some bound.

**Comment by AndrewVSutherland** [comment]
I like that idea.

**Comment by JohnCremona** [comment]
OK, I'll write it and you can take a look.

**Comment by JohnCremona** [comment]
I put in a bound of 10^12 on the norm of j.numerator_ideal() and a test failed -- a test which sepcifically was testing j factorizations!  It was this curve http://www.lmfdb.org/EllipticCurve/2.2.89.1/81.1/a/1 which as you can see has not problems.
So perhaps that norm bound is not an intelligent way of doing this.

**Comment by AndrewVSutherland** [comment]
OK, let's not try to complicate things now.  I have yet to find any curves over quadratic fields that pose a problem, I'd be happy to just supress the factorization if the degree is > 2 or to simply merge your pull request now, which ever you prefer.

**Comment by JohnCremona** [comment]
I'm putting in the test for field degree < 3 instead of norm size.
