### ISSUE TITLE
Internal server error when searching for modular form of weight 1

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1372]
Go to

http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/

click Gamma_1(N), type 1 in the weight box and press the make-new-table button.  This takes you to the URL http://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/ranges/?level=1-24&weight=1&group=1

which displays an internal server error.

**Comment by edgarcosta** [comment]
```
Exception on /ModularForm/GL2/Q/holomorphic/ranges/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/modular_forms/elliptic_modular_forms/views/emf_main.py", line 67, in browse_web_modform_spaces_in_ranges
    return _browse_web_modform_spaces_in_ranges(level=level,weight=weight,group=group)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/modular_forms/elliptic_modular_forms/views/emf_render_navigation.py", line 21, in _browse_web_modform_spaces_in_ranges
    return render_elliptic_modular_form_navigation_wp(**kwds)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/modular_forms/elliptic_modular_forms/views/emf_render_navigation.py", line 136, in render_elliptic_modular_form_navigation_wp
    info['table'][N][k]['dim_new'] = dim
KeyError: 1
```

**Comment by AndrewVSutherland** [comment]
Yup, I'm on it.

**Comment by AndrewVSutherland** [comment]
Fixed in pull request #1374.

**Comment by AndrewVSutherland** [comment]
Fix is now live on beta and works, pushing to prod.

**Comment by AndrewVSutherland** [comment]
Fix is now live on prod, closing.
