### ISSUE TITLE
Server error on EC page that occurs on beta.lmfdb.org but not www.lmfdb.org

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1492]
See http://beta.lmfdb.org/EllipticCurve/Q/download_all/102.c (reached by going to the home page of isogeny class 102.c and clicking the "download store data for all curves" option in the download box.

What is odd is that this works on www.lmfdb.org, and the software there should be identical to that on beta.lmfdb.org (as of now), so this suggests a difference in the data.

**Comment by AndrewVSutherland** [comment]
Traceback:

Traceback (most recent call last):
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/drew/github/lmfdb/lmfdb/elliptic_curves/elliptic_curve.py", line 515, in download_EC_all
    d = data[t]
KeyError: 'anlist'

**Comment by JohnCremona** [comment]
'anlist' is a key which was introduced in the new curves2 collection which is the same on both servers. That data field only exists for one curve in each isogeny class (the one with {'number':1}).

I confess that I never use the download_all capability (and did not write it) so had not tested that it still worked properly with the new collection.

It is possibly *chance* which makes this work on one but not the other, for isogeny classes:  the list of keys is obtained from the first curve found and then it tries to output those fields for all curves in the class.  This only makes sense if all curves in the class have the exact same fields.

I will fix it.

**Comment by JohnCremona** [comment]
This could be fixed by adding the 'aplist' and 'anlist' fields to every curve; I did not do that just to save space in the database, but perhaps that was unnecessary.  When they do exict, 'anlist' is a list of a_n for n<20 and 'aplist' a list of a_p for p<100, total 20+25=45 small integers.
However I'll first change the code.
