### ISSUE TITLE
Server error on symmetric power L-functions for CM elliptic curves

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1495]
To reproduce http://www.lmfdb.org/L/SymmetricPower/2/EllipticCurve/Q/27.a/
or go to http://www.lmfdb.org/L/EllipticCurve/Q/27.a/ and click symmetric square L-function in the related objects box.  It appears to be trying to display a not-implemented error message.  Traceback:

Traceback (most recent call last):
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/sage/sage-1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/drew/github/lmfdb/lmfdb/lfunctions/main.py", line 359, in l_function_ec_sym_page
    return render_single_Lfunction(SymmetricPowerLfunction, args, request)
  File "/home/drew/github/lmfdb/lmfdb/lfunctions/main.py", line 382, in render_single_Lfunction
    L = Lclass(**args)
  File "/home/drew/github/lmfdb/lmfdb/lfunctions/Lfunction.py", line 1389, in __init__
    'implemented')
TypeError: This Elliptic curve has complex multiplication and the symmetric power of its L-function is then not primitive. This has not yet been implemented

**Comment by JohnCremona** [comment]
I just noticed this Issue.  Not long ago I removed the symmetric power L-function links from elliptic curves and isogeny classes.  You can see this at http://www.lmfdb.org/EllipticCurve/Q/27/a/1 and http://www.lmfdb.org/EllipticCurve/Q/27/a .  But the L-function page itself does not implement the test.
According to the inventory, the (new) Lfunctions data does not have a CM flag but is has others which could be used in this case, e.g. it has the Sato-Tate group.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Before hiding the link, it would be good to fix the TypeError bug -- are you planning to make these changes or shall I?

**Comment by JohnCremona** [comment]
Don't wait for me. Thanks

**Comment by AndrewVSutherland** [comment]
Fixed by PR https://github.com/LMFDB/lmfdb/pull/1523.  BTW the TypeError is raised intentionally, it is not a bug.

**Comment by AndrewVSutherland** [comment]
Somehow this issue has resurfaced, currently http://www.lmfdb.org/L/SymmetricPower/2/EllipticCurve/Q/27.a/ is throwing a server error.  I will investigate.
