### ISSUE TITLE
Timeout attempting to load degree 16 number field page

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1662]
If you go to http://www.lmfdb.org/NumberField/?degree=16&discriminant=13307764731675384304522756096 you will see 4 number fields listed.  The last 3 links work fine, but the first times out, apparently while in pari_integeral_basis.  From the flasklog:

> Exception on /NumberField/16.0.13307764731675384304522756096.1 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/number_fields/number_field.py", line 411, in by_label
    return render_field_webpage({'label': nf_string_to_label(label)})
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/number_fields/number_field.py", line 302, in render_field_webpage
    data['frob_data'], data['seeram'] = frobs(nf.K())
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/number_fields/number_field.py", line 548, in frobs
    frob_at_p = residue_field_degrees_function(K)
  File "/home/lmfdb/lmfdb-git-prod/lmfdb/number_fields/number_field.py", line 532, in residue_field_degrees_function
    k1 = pari(K)
  File "sage/libs/pari/pari_instance.pyx", line 938, in sage.libs.pari.pari_instance.PariInstance.__call__ (/home/sage/sage-7.1/src/build/cythonized/sage/libs/pari/pari_instance.c:15581)
    return objtogen(s)
  File "sage/libs/pari/gen.pyx", line 9792, in sage.libs.pari.gen.objtogen (/home/sage/sage-7.1/src/build/cythonized/sage/libs/pari/gen.c:147906)
    return s._pari_()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field.py", line 3560, in _pari_
    return self.pari_nf()
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field.py", line 3528, in pari_nf
    f = pari([f, self._pari_integral_basis(important=important)])
  File "/home/sage/sage-7.1/local/lib/python2.7/site-packages/sage/rings/number_field/number_field.py", line 5178, in _pari_integral_basis
    B = f.nfbasis()
  File "sage/libs/pari/gen.pyx", line 7467, in sage.libs.pari.gen.gen.nfbasis (/home/sage/sage-7.1/src/build/cythonized/sage/libs/pari/gen.c:136512)
    pari_catch_sig_on()
  File "src/cysignals/signals.pyx", line 102, in cysignals.signals.sig_raise_exception (build/src/cysignals/signals.c:1158)
RuntimeError: Aborted

**Comment by jwj61** [comment]
I can see how to fix this one (and will work on it next week).  We have precomputed an integral basis already and can feed that to nfinit so the hard part of initializing is skipped.  The rest of the on-the-fly computation is pretty trivial.
