### ISSUE TITLE
Server error on degree 16 Number field L-functions

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#1692]
In the course of investigating #1687 I stumbled across the problems on the following 4 L-function pages:

http://www.lmfdb.org/L/NumberField/16.2.14383898168677573334952601242898232687.4/
http://www.lmfdb.org/L/NumberField/16.4.1055734705924451249419325715250393166653097913001.1/
http://www.lmfdb.org/L/NumberField/16.4.35504497706629289335330118915361516626281.21/
http://www.lmfdb.org/L/NumberField/16.0.1599229661124692101046354619853228081.5/

In each case the traceback is the same:

Traceback (most recent call last):
  File "/home/drew/sage-6.5-x86_64-Linux/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/drew/sage-6.5-x86_64-Linux/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/drew/sage-6.5-x86_64-Linux/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/drew/sage-6.5-x86_64-Linux/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/drew/sage-6.5-x86_64-Linux/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/drew/Dropbox/github/lmfdb/lmfdb/lfunctions/main.py", line 344, in l_function_nf_page
    return render_single_Lfunction(DedekindZeta, args, request)
  File "/home/drew/Dropbox/github/lmfdb/lmfdb/lfunctions/main.py", line 397, in render_single_Lfunction
    L = Lclass(**args)
  File "/home/drew/Dropbox/github/lmfdb/lmfdb/lfunctions/Lfunction.py", line 1094, in __init__
    self.res = RR(2 ** self.signature[0] * self.h * self.R) / self.w
TypeError: can't multiply sequence by non-int of type 'str'

**Comment by AndrewVSutherland** [comment]
Closed via #1692 (the problem was occurring because class number and regulator is not available for these fields).
