### ISSUE TITLE
RuntimeError in computing L-function zeros

### ISSUE THREAD

**Issue by JohnCremona** [LMFDB/lmfdb#339]
On http://beta.lmfdb.org/L/ModularForm/GL2/Q/holomorphic/15/8/0/a/0/ there are no zeros displayed and the flask log has this:

Exception on /L/Zeros/ModularForm/GL2/Q/holomorphic/15/8/0/a/0/ [GET]
Traceback (most recent call last):
 ...
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/main.py", line 709, in zeroesLfunction
    return render_zeroesLfunction(request, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/main.py", line 818, in render_zeroesLfunction
    website_zeros = L.compute_web_zeros(time_allowed = 10)
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/Lfunction_base.py", line 97, in compute_web_zeros
    allZeros = self.compute_checked_zeros(**kwargs)
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/Lfunction_base.py", line 108, in compute_checked_zeros
    return self.compute_lcalc_zeros(via_N = True, count = count, do_negative = do_negative or not self.selfdual)
  File "/home/lmfdb/lmfdb-git-beta/lmfdb/lfunctions/Lfunction_base.py", line 121, in compute_lcalc_zeros
    return self.sageLfunction.find_zeros_via_N(count, do_negative)
  File "sage/libs/lcalc/lcalc_Lfunction.pyx", line 362, in sage.libs.lcalc.lcalc_Lfunction.Lfunction.find_zeros_via_N (/home/lmfdb/sage2/src/build/cythonized/sage/libs/lcalc/lcalc_Lfunction.cpp:5159)
    sig_on()
  File "sage/ext/interrupt/interrupt.pyx", line 96, in sage.ext.interrupt.interrupt.sig_raise_exception (/home/lmfdb/sage2/src/build/cythonized/sage/ext/interrupt/interrupt.c:1037)
    raise RuntimeError(msg)
RuntimeError: Aborted

This works for me locally (same Sage version 6.8, same brnch of LMFDB code).

**Comment by JohnCremona** [comment]
Here is an example which crashes beta and also locally:

http://localhost:37777/L/Zeros/NumberField/8.0.1265625.1/

**Comment by davidfarmer** [comment]
Will be fixed when we get the zeros from the database
