### ISSUE TITLE
Server error when saving the test knowl

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#3867]
If you try to edit https://beta.lmfdb.org/knowledge/edit/test.text and save your changes it throws a server error due to a Byte/str issue as with many other recently reported issues related to the switch to python3:

Here is the traceback

`Exception on /knowledge/save [POST]
Traceback (most recent call last):
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/knowledge/main.py", line 598, in save_form
    k = Knowl(ID, saving=True, renaming=bool(NEWID))
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/knowledge/knowl.py", line 730, in __init__
    self.sed_safety = knowldb.check_sed_safety(ID)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/knowledge/knowl.py", line 463, in check_sed_safety
    matches = subprocess.check_output(['git', 'grep', """['"]%s['"]"""%(knowlid.replace('.',r'\.'))]).split('\n')
TypeError: a bytes-like object is required, not 'str'
[2020-06-05 22:06:43 UTC] 500 error on URL http://beta.lmfdb.org/knowledge/save ()`

**Comment by davidfarmer** [comment]
I had a server error when editing this knowl:

https://beta.lmfdb.org/knowledge/show/rcs.source.maass

**Comment by jwj61** [comment]
This is one of 3 places where (I think) we are getting errors because of the switch to sage 9/python 3.  I think beta should go back to sage 8/python 2 until they are fixed.

**Comment by AndrewVSutherland** [comment]
We may as well just fix the problems, which I think are all trivial fixes.  I just fixed this one, I look at the others and submit a PR shortly

**Comment by AndrewVSutherland** [comment]
For the record, the fix for this problem is to add the keyword parameter encoding='utf' to all the calls to subprocess.check_output.  But the encoding parameter is not supported in python 2 and the six package doesn't seem to provide a backward compatible version of check_output (it does for process_output), so I want to figure this out first.

**Comment by edgarcosta** [comment]
Once #3873 is merged, you will be able to edit the knowl
