### ISSUE TITLE
Search produces errors for abelian varieties over finite fields

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3874]
From the feedback page:

Entering x^4+16 in the jump box for https://beta.lmfdb.org/Variety/Abelian/Fq/ produces a server error.  The same error is also present on www.lmfdb.org.

**Comment by edgarcosta** [comment]
```
Traceback (most recent call last):
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/abvar/fq/main.py", line 67, in abelian_varieties
    return abelian_variety_search(info)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/utils/search_wrapper.py", line 127, in __call__
    return func(info)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/abvar/fq/main.py", line 571, in jump
    if cdict[2*g-i] != q**i * cdict[i]:
KeyError: 3
[2020-06-09 18:03:57 UTC] 500 error on URL http://beta.lmfdb.org/Variety/Abelian/Fq/?jump=x%5E4+%2B+16 ()
```
