### ISSUE TITLE
Backend problem

### ISSUE THREAD

**Issue by jwj61** [LMFDB/lmfdb#3886]
When trying to upsert to a database (using a script which used to work) I get:

Traceback (most recent call last):
  File "./addres.py", line 196, in <module>
    db.nf_fields.upsert({'label': str(ent['label'])}, {'res':ent['res']})
  File "/scratch/home/jj/lmfdb/lmfdb/backend/table.py", line 1390, in upsert
    self.log_db_change("upsert", query=query, data=data)
  File "/scratch/home/jj/lmfdb/lmfdb/backend/table.py", line 2423, in log_db_change
    self._db.log_db_change(operation, tablename=self.search_table, **data)
  File "/scratch/home/jj/lmfdb/lmfdb/lmfdb_database.py", line 272, in log_db_change
    uid = self.login()
  File "/scratch/home/jj/lmfdb/lmfdb/lmfdb_database.py", line 247, in login
    if not self.__editor:
AttributeError: 'LMFDBDatabase' object has no attribute '_LMFDBDatabase__editor'

**Comment by roed314** [comment]
I will take a look: it's a result of some recent changes I made.

**Comment by roed314** [comment]
See #3887
