### ISSUE TITLE
ECNF field validation issue

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#4019]
The ECNF code seems to try to construct a curve even if the label doesn't make sense.
```
Exception on /EllipticCurve/Q"ulno'ewnc/15680/bz/2/download/sage [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/ecnf/main.py", line 678, in ecnf_code_download
    response = make_response(ecnf_code(**args))
  File "/home/lmfdb/lmfdb-git-web/lmfdb/ecnf/main.py", line 711, in ecnf_code
    Ecode = E.code()
AttributeError: 'NoneType' object has no attribute 'code'
[2020-09-09 07:50:20 UTC] 500 error on URL https://www.lmfdb.org/EllipticCurve/Q%22ulno%27ewnc/15680/bz/2/download/sage?label=15680.bz2 ()
```
and
```
Exception on /EllipticCurve/Qx"l'xexfwv/1650/m/1 [GET]
Traceback (most recent call last):
  File "/home/lmfdb/lmfdb-git-web/lmfdb/ecnf/main.py", line 353, in show_ecnf
    nf_label = nf_string_to_label(nf)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/utils/search_parsing.py", line 751, in nf_string_to_label
    raise SearchParsingError('It is not a valid field name or label, or a defining polynomial.')
lmfdb.backend.utils.SearchParsingError: It is not a valid field name or label, or a defining polynomial.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/ecnf/main.py", line 355, in show_ecnf
    return search_input_error()
  File "/home/lmfdb/lmfdb-git-web/lmfdb/ecnf/main.py", line 548, in search_input_error
    bread = [('Elliptic curves', url_for(".index")) ('Search results', '.')]
TypeError: 'tuple' object is not callable
[2020-09-09 09:11:22 UTC] 500 error on URL https://www.lmfdb.org/EllipticCurve/Qx%22l%27xexfwv/1650/m/1
```

ps: this must have been a bot, but we should fix it regardless

**Comment by AndrewVSutherland** [comment]
I am working on this now
