### ISSUE TITLE
Search dealing with unwanted get arguments

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#4024]
```
[2020-09-10 12:44:28 UTC] 500 error on URL https://www.lmfdb.org/Character/Dirichlet/?modbrowse=https:%2F%2Fplyezlzf.ptvsbgediswojaschzynfskuz.com%2Fwduntdk%2F5 ()
Exception on /ModularForm/GL2/Q/holomorphic/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/classical_modular_forms/main.py", line 227, in index
    assert False
AssertionError
[2020-09-10 12:51:15 UTC] 500 error on URL https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/?search_type=https:%2F%2Faajm.okidxkhpzwvvs.com%2Fgzavyhj%2F8 ()

Exception on /Variety/Abelian/Fq/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/abvar/fq/main.py", line 68, in abelian_varieties
    assert False
AssertionError

[2020-09-10 12:31:02 UTC] 500 error on URL https://www.lmfdb.org/Variety/Abelian/Fq/?search_type=https:%2F%2Fjmxeto.yqxupvjlfon.com%2Fiurxkss%2F7 ()
Exception on /Character/Dirichlet/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/main.py", line 223, in render_Dirichletwebpage
    return render_DirichletNavigation()
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/main.py", line 94, in render_DirichletNavigation
    order_start = int(arg[0])
ValueError: invalid literal for int() with base 10: 'https://xmgexrfn.vbojhetabqmu.com/iqwz/9'

[2020-09-10 12:44:28 UTC] 500 error on URL https://www.lmfdb.org/Character/Dirichlet/?ordbrowse=https:%2F%2Fxmgexrfn.vbojhetabqmu.com%2Fiqwz%2F9 ()
Exception on /Character/Dirichlet/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/main.py", line 223, in render_Dirichletwebpage
    return render_DirichletNavigation()
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/main.py", line 82, in render_DirichletNavigation
    conductor_start = int(arg[0])
ValueError: invalid literal for int() with base 10: 'https://qlljxkaat.aiegkktbmumlxzhrchpvw.com/atgfpw/5'

[2020-09-10 12:44:28 UTC] 500 error on URL https://www.lmfdb.org/Character/Dirichlet/?condbrowse=https:%2F%2Fqlljxkaat.aiegkktbmumlxzhrchpvw.com%2Fatgfpw%2F5 ()
Exception on /Character/Dirichlet/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/main.py", line 223, in render_Dirichletwebpage
    return render_DirichletNavigation()
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/main.py", line 68, in render_DirichletNavigation
    modulus_start = int(arg[0])
ValueError: invalid literal for int() with base 10: 'https://plyezlzf.ptvsbgediswojaschzynfskuz.com/wduntdk/5'
```

**Comment by edgarcosta** [comment]
This should be fixed now
