### ISSUE TITLE
Timeout/error computing zeros of Dedekind zeta function of real quadratic field

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4215]
The URL https://www.lmfdb.org/L/Zeros/NumberField/2.2.568.1/ is showing up in the flasklog with the traceback:

```
Traceback (most recent call last):
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/lfunctions/main.py", line 871, in zerosLfunction
    return render_zerosLfunction(request, *args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/lfunctions/main.py", line 1009, in render_zerosLfunction
    website_zeros = L.compute_web_zeros(time_allowed = 10)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/lfunctions/Lfunction_base.py", line 61, in compute_web_zeros
    allZeros = self.compute_checked_zeros(**kwargs)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/lfunctions/Lfunction_base.py", line 73, in compute_checked_zeros
    return self.compute_lcalc_zeros(via_N = True, count = count, do_negative = do_negative or not self.selfdual)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/lfunctions/Lfunction_base.py", line 97, in compute_lcalc_zeros
    return self.sageLfunction.find_zeros_via_N(count, do_negative)
  File "sage/libs/lcalc/lcalc_Lfunction.pyx", line 359, in sage.libs.lcalc.lcalc_Lfunction.Lfunction.find_zeros_via_N (build/cythonized/sage/libs/lcalc/lcalc_Lfunction.cpp:5454)
    sig_on()
RuntimeError: Aborted
```

Given the small discriminant, it is surprising to me that this is failing, but we should either disable this computation or change the code to handle the error rather than throwing a server error.

There is no point in spending a lot of time trying to debug the lcalc call, if it is easy to fix great, but if not this problem will go away once the L-functions are precomputed.

**Comment by roed314** [comment]
https://www.lmfdb.org/L/Zeros/NumberField/2.2.568.1/ is no longer active, and gives a reasonable 404 error, so I'm closing this issue.
