### ISSUE TITLE
parse_bracketed_posints raises ZeroDivisionError

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#4436]
```
Exception on /NumberField/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.2/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.2/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.2/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.2/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.2/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.2/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/number_fields/number_field.py", line 359, in number_field_render_webpage
    return number_field_search(info)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/utils/search_wrapper.py", line 140, in __call__
    data = self.make_query(info, random)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/utils/search_wrapper.py", line 48, in make_query
    errpage = self.f(info, query)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/number_fields/number_field.py", line 788, in number_field_search
    parse_bracketed_posints(info,query,'class_group',check_divisibility='increasing',process=int)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/utils/search_parsing.py", line 95, in __call__
    rval = self.f(inp, query, qfield, *args, **kwds)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/utils/search_parsing.py", line 752, in parse_bracketed_posints
    if L[i+1] % L[i] != 0:
ZeroDivisionError: integer division or modulo by zero
[2021-02-11 13:01:48 UTC] 500 error on URL https://beta.lmfdb.org/NumberField/?hst=List&galois_group=D10&class_number=5&class_group=%5B0%2C1%2C5%5D&search_type=List ()
```

**Comment by jwj61** [comment]
Note, the pull request does not check to see if 1 is an invariant factor.  The knowl also does not rule out 1 being in the list, e.g., [1,5], but such a search will still return no results.
