### ISSUE TITLE
api server errors

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4612]
Clicking on any of the tables on https://www.lmfdb.org/api/ currently causes a server error, which appears to be related to the recent meta data changes:

```
Exception on /api/g2c_curves/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.2/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.2/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.2/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.2/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.2/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.2/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/api/api.py", line 347, in api_query
    search_schema = [(col, coll.col_type[col], coll.column_description(col))
  File "/home/lmfdb/lmfdb-git-web/lmfdb/api/api.py", line 347, in <listcomp>
    search_schema = [(col, coll.col_type[col], coll.column_description(col))
  File "/home/lmfdb/lmfdb-git-web/lmfdb/backend/table.py", line 2231, in column_description
    return current.get(col, "")
AttributeError: 'NoneType' object has no attribute 'get'
[2021-06-13 01:02:56 UTC] 500 error on URL https://www.lmfdb.org/api/g2c_curves/ ()
```

**Comment by roed314** [comment]
I'll take a look.

**Comment by roed314** [comment]
I updated the `col_description` column to `{}` for all the tables on prod where it was null.  We still need to push the column descriptions from beta (Edgar's going to work on a script for that next week I think), but at least we're not getting server errors now.
