### ISSUE TITLE
class groups and zeta zeros currently broken in production

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#4646]
There is currently no data listed on https://www.lmfdb.org/zeros/zeta/, whereas https://beta.lmfdb.org/zeros/zeta is fine.  There is a corresponding error in the flasklog on prodweb2

```
Exception on /zeros/zeta/list [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.2/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.2/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.2/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.2/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.2/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.2/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/zeros/zeta/zetazeros.py", line 90, in list_zeros
    zeros = zeros_starting_at_t(t, limit)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/zeros/zeta/platt_zeros.py", line 167, in zeros_starting_at_t
    c = sqlite3.connect(db_location).cursor()
sqlite3.OperationalError: unable to open database file
[2021-06-27 11:30:49 UTC] 500 error on URL https://www.lmfdb.org/zeros/zeta/list?N=&t=&limit=100 ()
```

@edgarcosta is this caused by some of the recent fiddling we were doing with the GCS buckets?

**Comment by AndrewVSutherland** [comment]
The class group data is having the same problem, which I think is being caused by a permission issue.

**Comment by edgarcosta** [comment]
I will look into it. We ended up not changing anything. So I think it is
unrelated.

**Comment by edgarcosta** [comment]
A reboot of prodweb2 solved the issue.
