### ISSUE TITLE
Some bianch modular forms are generating server errors

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#4647]
Here is the traceback for https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.163.1/900.1/a/
```
Exception on /ModularForm/GL2/ImaginaryQuadratic/2.0.163.1/900.1/a/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.3/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.3/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.3/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.3/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.3/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.3/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/bianchi_modular_forms/bianchi_modular_form.py", line 567, in render_bmf_webpage
    data = WebBMF.by_label(label, max_eigs=numeigs)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/bianchi_modular_forms/web_BMF.py", line 111, in by_label
    return WebBMF(data, max_eigs)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/bianchi_modular_forms/web_BMF.py", line 100, in __init__
    self.make_form(max_eigs)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/bianchi_modular_forms/web_BMF.py", line 235, in make_form
    curve_bc_parts = [split_lmfdb_label(lab) for lab in curve_bc]
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/bianchi_modular_forms/web_BMF.py", line 235, in <listcomp>
    curve_bc_parts = [split_lmfdb_label(lab) for lab in curve_bc]
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/elliptic_curves/web_ec.py", line 33, in split_lmfdb_label
    return lmfdb_label_regex.match(lab).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
[2021-06-27 14:15:35 UTC] 500 error on URL https://beta.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/2.0.163.1/900.1/a/ ()
```

**Comment by JohnCremona** [comment]
OK, I know what is causing this -- some BMFs do not have elliptic curves but the fairly short list of those which do not is hard-wored, and needs updating.

**Comment by JohnCremona** [comment]
#4650 should fix this
