### ISSUE TITLE
Sato-Tate stats broken

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#5099]
```
Exception on /SatoTateGroup/stats [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/sato_tate_groups/main.py", line 543, in statistics
    return render_template("display_stats.html", info=STStats(), title=title, bread=bread, learnmore=learnmore_list())
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/display_stats.html", line 1, in top-level template code
    {% extends 'homepage.html' %}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/homepage.html", line 19, in top-level template code
    <div class="{{ [L,'nodisplay','code','codebox'] | join(' ')}}">{% for line in lines %}{{prompt}}:&nbsp;{{line}}<br /><div style="margin: 0; padding: 0; height: 0;">&nbsp;</div>{# this div is a workaround for a copy-tex bug where if a code block followed a hidden code block followed by math was selected and copied the hidden block would be also it is important that it has display: block #}{% endfor %}</div>
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/base.html", line 148, in top-level template code
    {% block body -%}{%- endblock body %}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/homepage.html", line 242, in block "body"
    {% block content -%}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/display_stats.html", line 16, in block "content"
    {% for d in info.distributions %}
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
  File "sage/misc/lazy_attribute.pyx", line 127, in sage.misc.lazy_attribute._lazy_attribute.__get__ (build/cythonized/sage/misc/lazy_attribute.c:1984)
    result = self.f(a)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/utils/display_stats.py", line 645, in distributions
    return [self.prep(attr) for attr in self.stat_list]
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/utils/display_stats.py", line 645, in <listcomp>
    return [self.prep(attr) for attr in self.stat_list]
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/utils/display_stats.py", line 624, in prep
    data = self.display_data(**attr)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/utils/display_stats.py", line 577, in display_data
    headers, grid = table._get_values_counts(cols, constraint, split_list=False, formatter=formatter, query_formatter=query_formatter, base_url=base_url, buckets=buckets)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/backend/statstable.py", line 1772, in _get_values_counts
    D = make_count_dict(values, count)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/backend/statstable.py", line 1747, in make_count_dict
    query = base_url + "&".join(query_formatter[col](val) for col, val in zip(cols, values))
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/backend/statstable.py", line 1747, in <genexpr>
    query = base_url + "&".join(query_formatter[col](val) for col, val in zip(cols, values))
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/sato_tate_groups/main.py", line 1189, in <lambda>
    query_formatters = {"component_group": (lambda comp: "component_group=%s" % compunformatter(comp)),
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/sato_tate_groups/main.py", line 1150, in compunformatter
    n, k = compdata(comp)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/sato_tate_groups/main.py", line 1145, in compdata
    return [int(x) for x in gapidre.findall(comp)[0]]
IndexError: list index out of range
[2022-04-07 20:30:27 UTC] 500 error on URL https://beta.lmfdb.org/SatoTateGroup/stats ()
```

**Comment by edgarcosta** [comment]
https://beta.lmfdb.org/SatoTateGroup/stats

Is still broken for me.

**Comment by roed314** [comment]
This is from some new abelian style labels (e.g. `ab/2914`).  I'm working on it.

**Comment by roed314** [comment]
See #5123.
