### ISSUE TITLE
Server error on some finite abelian groups

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5214]
From the flasklog on beta:

```
Exception on /Groups/Abstract/ab/2.2.2.4.4.4 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.4/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/main.py", line 670, in by_abelian_label
    return render_abstract_group("ab/" + canonical_label, data=primary)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/main.py", line 1147, in render_abstract_group
    properties=gp.properties(),
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/web_groups.py", line 687, in properties
    props.append((None, self.image()))
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/web_groups.py", line 1465, in image
    circles, R = find_packing([(c.size, c.order) for c in self.conjugacy_classes])
  File "sage/misc/lazy_attribute.pyx", line 127, in sage.misc.lazy_attribute._lazy_attribute.__get__ (build/cythonized/sage/misc/lazy_attribute.c:1984)
    result = self.f(a)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/web_groups.py", line 835, in conjugacy_classes
    for c in self.G.ConjugacyClasses()
AttributeError: 'LiveAbelianGroup' object has no attribute 'ConjugacyClasses'
[2022-09-22 11:31:02 UTC] 500 error on URL https://beta.lmfdb.org/Groups/Abstract/ab/2.2.2.4.4.4 ()
```

**Comment by AndrewVSutherland** [comment]
You can reproduce the error by visiting https://beta.lmfdb.org/Groups/Abstract/ab/2.2.2.4.4.4.

**Comment by roed314** [comment]
Yep, I already made #5212 last night.  😄
