### ISSUE TITLE
Error on p-adic field with incorrect label

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5247]
```
Exception on /padicField/2.16.36.3 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/local_fields/main.py", line 185, in by_label
    return render_field_webpage({'label': label})
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/local_fields/main.py", line 364, in render_field_webpage
    'subfields': format_subfields(data['subfield'],data['subfield_mult'],p),
KeyError: 'subfield'
[2022-10-29 14:28:15 UTC] 500 error on URL https://beta.lmfdb.org/padicField/2.16.36.3 ()
```
Indeed, there is no `2.16.36.3` in the database, but I'm confused why we're getting to this point: we should raise a flash error further up in `render_field_webpage`.

**Comment by jwj61** [comment]
I am working on these fields.  I tried an upload, there was a problem, so I deleted the offending fields while I sort out the error.  The fields should (hopefully) be working in a day or so.
