### ISSUE TITLE
Server error on BMF double banana test

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5306]
https://www.lmfdb.org/ModularForm/GL2/ImaginaryQuadratic/banana/banana is throwing a server error (it should throw a 404).

This is causing the flasklog to fill up with errors when probed by (possibly nefarious) bots (they are not sending us bananas, but appear to be attempting an SQL injection of some sort).  None of these cause us any harm (they are not labels of number fields or Bianchi modular forms), but the server errors show up in the flask log which triggers alerts that have to be investigated.

This should be easy to fix, we just need to add more validation to some of the bmf routes.  Here is an example traceback
```
Traceback (most recent call last):
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/bianchi_modular_forms/bianchi_modular_form.py", line 314, in render_bmf_space_webpage
    (field_pretty(field_label), url_for(".render_bmf_field_dim_table_gl2", field_label=field_label)),
  File "sage/misc/cachefunc.pyx", line 990, in sage.misc.cachefunc.CachedFunction.__call__
    w = self.f(*args, **kwds)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/number_fields/web_number_field.py", line 213, in field_pretty
    d, r, D, _ = label.split('.')
ValueError: not enough values to unpack (expected 4, got 1)
```

**Comment by JohnCremona** [comment]
Fixed in PR#5307
