### ISSUE TITLE
'WebAbstractSubgroup' object has no attribute 'subgroup_tex'

### ISSUE THREAD

**Issue by edgarcosta** [LMFDB/lmfdb#5343]
````
Exception on /Groups/Abstract/sub/120.10.2.b1 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/main.py", line 678, in by_subgroup_label
    return render_abstract_subgroup(label)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/main.py", line 1163, in render_abstract_subgroup
    seq = WebAbstractSubgroup(label)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/web_groups.py", line 1712, in __init__
    s = self.subgroup_tex
AttributeError: 'WebAbstractSubgroup' object has no attribute 'subgroup_tex'
[2023-02-26 14:44:54 UTC] 500 error on URL https://beta.lmfdb.org/Groups/Abstract/sub/120.10.2.b1 ()
```

**Comment by jwj61** [comment]
There is no such subgroup.  The question then is what referred the person to that url?  Aside from figuring that out, I suppose there should be a flash error of not in database.

**Comment by edgarcosta** [comment]
My guess it was typed by hand or a copy paste mistake

**Comment by jenpaulhus** [comment]
I think we can now close this issue as it is not reproducible in the newest beta version.

If you search for all subgroups of index 2 of 120.10: 
https://beta.lmfdb.org/Groups/Abstract/?hst=Subgroups&ambient=120.10&quotient_order=2&search_type=Subgroups
you find 3 subgroups none of which produce an error.
