### ISSUE TITLE
server error in ModularCurves

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5660]
https://beta.lmfdb.org/ModularCurve/Q/30.60.3.b.1/ is throwing the following error:
```
Exception on /ModularCurve/Q/30.60.3.b.1/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/modular_curves/main.py", line 140, in by_label
    return render_template(
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/modular_curves/templates/modcurve.html", line 1, in top-level template code
    {% extends 'homepage.html' %}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/homepage.html", line 19, in top-level template code
    <div class="{{ [L,'nodisplay','code','codebox'] | join(' ')}}">{% for line in lines %}{% if lines | length == 1 %}{{prompt}}:&nbsp;{% endif %}{{line}}<br /><div style="margin: 0; padding: 0; height: 0;">&nbsp;</div>{# this div is a workaround for a copy-tex bug where if a code block followed a hidden code block followed by math was selected and copied the hidden block would be also it is important that it has display: block #}{% endfor %}</div>
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/base.html", line 182, in top-level template code
    {% block body -%}{%- endblock body %}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/homepage.html", line 246, in block 'body'
    {% block content -%}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/modular_curves/templates/modcurve.html", line 87, in block 'content'
    {% set models = curve.formatted_models %}
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
  File "sage/misc/lazy_attribute.pyx", line 127, in sage.misc.lazy_attribute._lazy_attribute.__get__
    result = self.f(a)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/modular_curves/web_curve.py", line 452, in formatted_models
    return [formatted_model(m) for m in self.models_to_display]
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/modular_curves/web_curve.py", line 452, in <listcomp>
    return [formatted_model(m) for m in self.models_to_display]
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/modular_curves/web_curve.py", line 192, in formatted_model
    assert F.monomial_coefficient(w**2) == -1
AssertionError
[2023-09-05 13:42:11 UTC] 500 error on URL https://beta.lmfdb.org/ModularCurve/Q/30.60.3.b.1/ ()
```

**Comment by AndrewVSutherland** [comment]
Fixed by #5661
