### ISSUE TITLE
Trivial Dirichlet character

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5677]
There's a server error when visiting https://www.lmfdb.org/Character/Dirichlet/1/1
```
Exception on /Character/Dirichlet/1/1 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/main.py", line 507, in render_Dirichletwebpage
    webchar, bread_crumbs = make_webchar(args, get_bread=True)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/main.py", line 376, in make_webchar
    return WebDBDirichletCharacter(**args), bread_crumbs
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 957, in __init__
    WebDBDirichlet.__init__(self, **kwargs)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 570, in __init__
    self._compute()
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 577, in _compute
    self._populate_from_db()
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 600, in _populate_from_db
    self._set_kernel_field_poly()
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 690, in _set_kernel_field_poly
    list_coeffs = self.chi.kernel_field_poly().list()
  File "sage/misc/cachefunc.pyx", line 2301, in sage.misc.cachefunc.CachedMethodCallerNoArgs.__call__
    self.cache = f(self._instance)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/TinyConrey.py", line 256, in kernel_field_poly
    pol = self.G.galoissubcyclo(self.G.charker(self.chi_pari))
  File "cypari2/auto_gen.pxi", line 12631, in cypari2.gen.Gen_base.galoissubcyclo
  File "cypari2/handle_error.pyx", line 213, in cypari2.handle_error._pari_err_handle
cypari2.handle_error.PariError: incorrect type in galoissubcyclo [H not in HNF] (t_MAT)
[2023-10-05 10:01:55 UTC] 500 error on URL https://www.lmfdb.org/Character/Dirichlet/1/1
```

**Comment by AndrewVSutherland** [comment]
This has been fixed, see the duplicate issue #5687 which was resolved by #5688
