### ISSUE TITLE
Dirichlet character pages for modulus 1 and 2 broken

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5687]
The pages 

https://www.lmfdb.org/Character/Dirichlet/1/a
https://www.lmfdb.org/Character/Dirichlet/2/a

are currently throwing server errors on production (but work fine on beta).  The code and the data are the same on both, so I'm guessing this is down to a software difference.  prodweb1 and prodweb2 are not running the same versions of Sage and Pari/GP as beta (the problem appears to be in the pari code that is being used in [TinyConrey.py](https://github.com/LMFDB/lmfdb/blob/0cf2fb20200ee22f1333dcb6dbe78d897bc998b3/lmfdb/characters/TinyConrey.py)).

```
Exception on /Character/Dirichlet/2/a [GET]
Traceback (most recent call last):
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/main.py", line 439, in render_Dirichletwebpage
    info = WebDBDirichletOrbit(**args).to_dict()
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 1131, in __init__
    self._populate_from_db()  # this is the meat
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 1153, in _populate_from_db
    self._set_kernel_field_poly(orbit_data)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/web_character.py", line 1177, in _set_kernel_field_poly
    list_coeffs = chi.kernel_field_poly().list()
  File "sage/misc/cachefunc.pyx", line 2301, in sage.misc.cachefunc.CachedMethodCallerNoArgs.__call__
    self.cache = f(self._instance)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/TinyConrey.py", line 256, in kernel_field_poly
    pol = self.G.galoissubcyclo(self.G.charker(self.chi_pari))
  File "cypari2/auto_gen.pxi", line 12631, in cypari2.gen.Gen_base.galoissubcyclo
  File "cypari2/handle_error.pyx", line 213, in cypari2.handle_error._pari_err_handle
cypari2.handle_error.PariError: incorrect type in galoissubcyclo [H not in HNF] (t_MAT)
[2023-10-12 10:25:59 UTC] 500 error on URL https://www.lmfdb.org/Character/Dirichlet/2/a ()
```

**Comment by AndrewVSutherland** [comment]
This is now fixed.
