### ISSUE TITLE
Error downloading when genus larger than two

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5751]
We recently saw this in the error log:
```
Exception on /Belyi/download_galmap_to_magma/7T7-5.2_3.3.1_4.3-a [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/belyi/main.py", line 609, in belyi_galmap_magma_download
    return Belyi_download().download_galmap_magma(label)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/belyi/main.py", line 532, in download_galmap_magma
    raise NotImplementedError("for genus > 2")
NotImplementedError: for genus > 2
[2023-11-29 17:30:19 UTC] 500 error on URL https://beta.lmfdb.org/Belyi/download_galmap_to_magma/7T7-5.2_3.3.1_4.3-a ()
```

If downloads aren't implemented for large genus, we should still catch the error and redirect to an appropriate page.

**Comment by BarinderBanwait** [comment]
linked PR fixes this issue; an error will be flashed on screen if a download of a belyi map of genus > 2 is attempted (even though this is currently impossible because there are no such belyi maps in the DB)
