### ISSUE TITLE
Server error on group page

### ISSUE THREAD

**Issue by AndrewVSutherland** [LMFDB/lmfdb#5967]
https://beta.lmfdb.org/Groups/Abstract/sub/1472.1055.4.y1.a1 causes the following error:
```
Exception on /Groups/Abstract/sub/1472.1055.4.y1.a1 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/main.py", line 765, in by_subgroup_label
    return render_abstract_subgroup(label)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/main.py", line 1519, in render_abstract_subgroup
    return render_template(
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/templates/abstract-show-subgroup.html", line 1, in top-level template code
    {% extends "homepage.html" %}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/homepage.html", line 19, in top-level template code
    <div class="{{ [L,'nodisplay','code','codebox'] | join(' ')}}">{% for line in lines %}{% if lines | length == 1 %}{{prompt}}:&nbsp;{% endif %}{{line}}<br /><div style="margin: 0; padding: 0; height: 0;">&nbsp;</div>{# this div is a workaround for a copy-tex bug where if a code block followed a hidden code block followed by math was selected and copied the hidden block would be also it is important that it has display: block #}{% endfor %}</div>
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/base.html", line 187, in top-level template code
    {% block body -%}{%- endblock body %}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/homepage.html", line 246, in block 'body'
    {% block content -%}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/templates/abstract-show-subgroup.html", line 172, in block 'content'
    <tr><td>$\card{\operatorname{res}({{S}})}$</td><td>{{info.pos_int_and_factor(seq.sub.aut_order / seq.aut_weyl_index)}}</td></tr>
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/utils/web_display.py", line 231, in pos_int_and_factor
    n = ZZ(n)
  File "sage/structure/parent.pyx", line 897, in sage.structure.parent.Parent.__call__
    return mor._call_(x)
  File "sage/rings/rational.pyx", line 4175, in sage.rings.rational.Q_to_Z._call_
    raise TypeError("no conversion of this rational to integer")
TypeError: no conversion of this rational to integer
[2024-03-24 09:53:20 UTC] 500 error on URL https://beta.lmfdb.org/Groups/Abstract/sub/1472.1055.4.y1.a1 ()
```

**Comment by AndrewVSutherland** [comment]
Another one (possibly unrelated): https://beta.lmfdb.org/Groups/Abstract/auto_gens/1024.bck
```
Exception on /Groups/Abstract/auto_gens/1024.bck [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/main.py", line 754, in auto_gens
    return render_template(
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/templates/auto_gens_page.html", line 2, in top-level template code
    {% extends "homepage.html" %}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/homepage.html", line 19, in top-level template code
    <div class="{{ [L,'nodisplay','code','codebox'] | join(' ')}}">{% for line in lines %}{% if lines | length == 1 %}{{prompt}}:&nbsp;{% endif %}{{line}}<br /><div style="margin: 0; padding: 0; height: 0;">&nbsp;</div>{# this div is a workaround for a copy-tex bug where if a code block followed a hidden code block followed by math was selected and copied the hidden block would be also it is important that it has display: block #}{% endfor %}</div>
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/base.html", line 187, in top-level template code
    {% block body -%}{%- endblock body %}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/homepage.html", line 246, in block 'body'
    {% block content -%}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/templates/auto_gens_page.html", line 22, in block 'content'
    {% set aut_data = gp.auto_gens_data() %}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/web_groups.py", line 2013, in auto_gens_data
    orders = [z.Order() for z in auts]
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/web_groups.py", line 2013, in <listcomp>
    orders = [z.Order() for z in auts]
  File "sage/libs/gap/element.pyx", line 2677, in sage.libs.gap.element.GapElement_MethodProxy.__call__
    return GapElement_Function.__call__(self, self.first_argument)
  File "sage/libs/gap/element.pyx", line 2523, in sage.libs.gap.element.GapElement_Function.__call__
    sig_on()
sage.libs.gap.util.GAPError: Error, no method found! Error, no 1st choice method found for `ImagesRepresentative' on 2 arguments
The 2nd argument is 'fail' which might point to an earlier problem
[2024-04-14 13:08:03 UTC] 500 error on URL https://beta.lmfdb.org/Groups/Abstract/auto_gens/1024.bck ()
```

**Comment by jwj61** [comment]
I don't think there is a link to this url (the only one I know of is suppressed because we don't have details about the automorphism group).  The fix will be to redirect to an error page.

**Comment by AndrewVSutherland** [comment]
It is probably being hit by a crawler that found a page with this URL in it at some point in the past.

**Comment by jenpaulhus** [comment]
I don't think we should keep creating temporary fixes on the groups pages where we redirect to error pages.  The issue for both of these errors are data issues we are already aware of.  Once the data is fixed, the pages will work.  If we keep putting up temporary patches to things and we don't keep really careful notes about what we've done, we're not going to remember to undo them all.

 (Also see Zulip discussion for both these errors.)

**Comment by jwj61** [comment]
The two referenced pages work now.
