### ISSUE TITLE
Catch error in conrey character code

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#5981]
I've seen this kind of error repeatedly in the flasklogs:

```
Exception on /ModularForm/GL2/Q/holomorphic/34/3/e/b/24/2/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-10.1/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/classical_modular_forms/main.py", line 565, in by_url_embedded_newform_label
    return render_embedded_newform_webpage(newform_label, embedding_label)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/classical_modular_forms/main.py", line 391, in render_embedded_newform_webpage
    newform = WebNewform.by_label(newform_label,
  File "/home/lmfdb/lmfdb-git-web/lmfdb/classical_modular_forms/web_newform.py", line 550, in by_label
    return WebNewform(data, embedding_label=embedding_label)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/classical_modular_forms/web_newform.py", line 216, in __init__
    chi = ConreyCharacter(self.level, int(self.char_conrey))
  File "/home/lmfdb/lmfdb-git-web/lmfdb/characters/TinyConrey.py", line 103, in __init__
    assert gcd(modulus, number)==1
AssertionError
[2024-04-12 11:49:14 UTC] 500 error on URL https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/34/3/e/b/24/2/ ()
```

We should catch it or preempt it and show an actual error message (or just a 404).

**Comment by roed314** [comment]
Resolved by #5982.
