### ISSUE TITLE
Error in CMFs with high level

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#6038]
@thealexcowan, @AndrewVSutherland: this looks like a consequence of recent changes.  I'm not able to look at it this weekend, but can try over the week if one of you doesn't get to it first.

```
Exception on /ModularForm/GL2/Q/holomorphic/100361/2/a/a/ [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/classical_modular_forms/main.py", line 540, in by_url_newform_label
    return render_newform_webpage(label)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/classical_modular_forms/main.py", line 376, in render_newform_webpage
    return render_template("cmf_newform.html",
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/classical_modular_forms/templates/cmf_newform.html", line 1, in top-level template code
    {% extends 'cmf_newform_common.html' %}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/classical_modular_forms/templates/cmf_newform_common.html", line 1, in top-level template code
    {% extends 'homepage.html' %}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/homepage.html", line 19, in top-level template code
    <div class="{{ [L,'nodisplay','code','codebox'] | join(' ')}}">{% for line in lines %}{% if lines | length == 1 %}{{prompt}}:&nbsp;{% endif %}{{line}}<br /><div style="margin: 0; padding: 0; height: 0;">&nbsp;</div>{# this div is a workaround for a copy-tex bug where if a code block followed a hidden code block followed by math was selected and copied the hidden block would be also it is important that it has display: block #}{% endfor %}</div>
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/base.html", line 187, in top-level template code
    {% block body -%}{%- endblock body %}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/templates/homepage.html", line 246, in block 'body'
    {% block content -%}
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/classical_modular_forms/templates/cmf_newform_common.html", line 68, in block 'content'
    <td> {{ newform.field_display() | safe }}</td>
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/classical_modular_forms/web_newform.py", line 576, in field_display
    if m and (d != 2 or self.hecke_ring_cyclotomic_generator):
AttributeError: 'WebNewform' object has no attribute 'hecke_ring_cyclotomic_generator'
[2024-05-12 01:21:53 UTC] 500 error on URL https://beta.lmfdb.org/ModularForm/GL2/Q/holomorphic/100361/2/a/a/ ()
```

**Comment by AndrewVSutherland** [comment]
I think this happened while I was in the process of updating multiple files and it shouldn't happen now, are you able to reproduce it?

**Comment by roed314** [comment]
No, I was just copying this from the flasklog.  Indeed, this seems to pass now.
