### ISSUE TITLE
Galois Group page issue

### ISSUE THREAD

**Issue by jenpaulhus** [LMFDB/lmfdb#6217]
From the feedback page, the following page produces an error (and fails on beta too).  
https://www.lmfdb.org/GaloisGroup/17T6

This looks possibly different than #6177 so posting here.

```
Exception on /GaloisGroup/17T6 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/galois_groups/main.py", line 82, in by_label
    return render_group_webpage({'label': label})
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/galois_groups/main.py", line 265, in render_group_webpage
    data['cclasses'] = wgg.conjclasses
  File "sage/misc/lazy_attribute.pyx", line 127, in sage.misc.lazy_attribute._lazy_attribute.__get__
    result = self.f(a)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/galois_groups/transitive_group.py", line 205, in conjclasses
    isom = self.getisom
  File "sage/misc/lazy_attribute.pyx", line 127, in sage.misc.lazy_attribute._lazy_attribute.__get__
    result = self.f(a)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/galois_groups/transitive_group.py", line 183, in getisom
    return wag.G.GroupHomomorphismByImagesNC(self.gapgroupnt(), wag.G_gens(), imgs)
  File "sage/misc/lazy_attribute.pyx", line 127, in sage.misc.lazy_attribute._lazy_attribute.__get__
    result = self.f(a)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/web_groups.py", line 389, in G
    return libgap.Group(gens)
  File "sage/libs/gap/element.pyx", line 2523, in sage.libs.gap.element.GapElement_Function.__call__
    sig_on()
sage.libs.gap.util.GAPError: Error, usage: Group(<gen>,...), Group(<gens>), Group(<gens>,<id>)
[2024-10-26 12:56:49 UTC] 500 error on URL https://beta.lmfdb.org/GaloisGroup/17T6 ()
```

**Comment by edgarcosta** [comment]
Perhaps triggered by the data fix?

**Comment by jwj61** [comment]
I don't think so.  This is the line where we construct an isomorphism between the transitive group and an abstract group.  Drilling down, the error seems to be on the abstract group side where we ask for its generators (wag.G_gens).  The abstract group is 4080.a.  If you create this object (abstract group 4080.a) and try to access the group in gap using the method G, then it produces an error.

**Comment by jwj61** [comment]
While we wait for a fix in finite groups, this is fixed on beta by deleting isomorphism data.  To propogate to prod, the table gps_transitive needs to be uploaded.
