### ISSUE TITLE
Missing minimal sibling

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#6222]
From the flasklog:
```
Exception on /NumberField/12.4.871612548828125.2 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/number_fields/number_field.py", line 744, in by_label
    return render_field_webpage({'label': nflabel})
  File "/home/lmfdb/lmfdb-git-web/lmfdb/number_fields/number_field.py", line 721, in render_field_webpage
    return render_template("nf-show-field.html", properties=properties, title=title, bread=bread, code=nf.code, friends=info.pop('friends'), downloads=downloads, learnmore=learnmore, info=info, formatfield=formatfield, KNOWL_ID="nf.%s" % label)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lmfdb/lmfdb-git-web/lmfdb/number_fields/templates/nf-show-field.html", line 1, in top-level template code
    {% extends 'homepage.html' %}
  File "/home/lmfdb/lmfdb-git-web/lmfdb/templates/homepage.html", line 19, in top-level template code
    <div class="{{ [L,'nodisplay','code','codebox'] | join(' ')}}">{% for line in lines %}{% if lines | length == 1 %}{{prompt}}:&nbsp;{% endif %}{{line}}<br /><div style="margin: 0; padding: 0; height: 0;">&nbsp;</div>{# this div is a workaround for a copy-tex bug where if a code block followed a hidden code block followed by math was selected and copied the hidden block would be also it is important that it has display: block #}{% endfor %}</div>
  File "/home/lmfdb/lmfdb-git-web/lmfdb/templates/base.html", line 188, in top-level template code
    {% block body -%}{%- endblock body %}
  File "/home/lmfdb/lmfdb-git-web/lmfdb/templates/homepage.html", line 246, in block 'body'
    {% block content -%}
  File "/home/lmfdb/lmfdb-git-web/lmfdb/number_fields/templates/nf-show-field.html", line 205, in block 'content'
    {{KNOWL('nf.minimal_sibling', title='Minimal sibling')}}: <td>{{ nf.minimal_sibling() | safe }}</tr>
  File "/home/lmfdb/lmfdb-git-web/lmfdb/number_fields/web_number_field.py", line 457, in minimal_sibling
    return formatfield(self._data['minimal_sibling'], show_poly=True)
KeyError: 'minimal_sibling'
[2024-10-31 15:47:12 UTC] 500 error on URL https://www.lmfdb.org/NumberField/12.4.871612548828125.2 ()
```
There's also a similar error on https://www.lmfdb.org/NumberField/12.4.175927764892578125.2

**Comment by jwj61** [comment]
There were a few thousand where this was missing.  It has now been added.  To fix on prod, upload the table nf_fields

**Comment by AndrewVSutherland** [comment]
Copy to proddb in progress...

**Comment by AndrewVSutherland** [comment]
There was a hiccup with the copy, but it has now been completed (thanks to @edgarcosta), and both of the URLs above now work.
