### ISSUE TITLE
Timeouts on live group pages

### ISSUE THREAD

**Issue by roed314** [LMFDB/lmfdb#6223]
I think there's utility in keeping live group pages (especially for abelian groups and groups of order less than 2000 that aren't in the database).  But certain things do time out, causing annoying errors in the flasklog.  This issue is for brainstorming ways to improve the situation.

For example, we recently got timeouts on [119633.1](https://beta.lmfdb.org/Groups/Abstract/119633.1) (a large prime cyclic group) from trying to identify its automorphism group, and on [1060502.1](https://beta.lmfdb.org/Groups/Abstract/1060502.1) (nonabelian group, order twice a prime) from listing conjugacy classes.  One easy rule: no prime divisor larger than 2000.  More broadly, we should stress test various [factorization patterns](https://docs.gap-system.org/pkg/smallgrp/doc/chap1.html).

**Comment by roed314** [comment]
We should also probably not compute `monomial`:
```
Exception on /Groups/Abstract/1536.408640943 [GET]
Traceback (most recent call last):
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sage/sage-9.7/local/var/lib/sage/venv-python3.10.5/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/main.py", line 700, in by_label
    return render_abstract_group(label)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/main.py", line 1555, in render_abstract_group
    info["boolean_characteristics_string"] = create_boolean_string(gp)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/main.py", line 560, in create_boolean_string
    props = find_props(
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/main.py", line 193, in find_props
    if not getattr(gp, prop, None) or prop in noted or prop not in show:
  File "sage/misc/lazy_attribute.pyx", line 127, in sage.misc.lazy_attribute._lazy_attribute.__get__
    result = self.f(a)
  File "/home/lmfdb/lmfdb-git-dev/lmfdb/groups/abstract/web_groups.py", line 448, in monomial
    return bool(self.G.IsMonomial())
  File "sage/libs/gap/element.pyx", line 2677, in sage.libs.gap.element.GapElement_MethodProxy.__call__
    return GapElement_Function.__call__(self, self.first_argument)
  File "sage/libs/gap/element.pyx", line 2523, in sage.libs.gap.element.GapElement_Function.__call__
    sig_on()
RuntimeError: Aborted
[2024-12-14 11:29:03 UTC] 500 error on URL https://beta.lmfdb.org/Groups/Abstract/1536.408640943 ()
```
